// GENERATED by npm run upload-stock — do not edit by hand.
// Goth-culture stock portraits hosted on Cloudinary (folder nocturne/stock).
// Sources: CC-BY / CC-BY-SA images via Openverse (see stockCandidates.json).
export const STOCK_FEMME = [
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632490/nocturne/stock/goth-01.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632492/nocturne/stock/goth-02.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632493/nocturne/stock/goth-03.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632495/nocturne/stock/goth-04.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632496/nocturne/stock/goth-05.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632498/nocturne/stock/goth-06.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632499/nocturne/stock/goth-07.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632500/nocturne/stock/goth-08.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632502/nocturne/stock/goth-09.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632503/nocturne/stock/goth-10.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632505/nocturne/stock/goth-11.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632506/nocturne/stock/goth-12.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632507/nocturne/stock/goth-13.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632509/nocturne/stock/goth-14.jpg"
];

export const STOCK_MASC = [
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632510/nocturne/stock/goth-15.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632511/nocturne/stock/goth-16.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632513/nocturne/stock/goth-17.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632514/nocturne/stock/goth-18.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632516/nocturne/stock/goth-19.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632518/nocturne/stock/goth-20.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632518/nocturne/stock/goth-21.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632519/nocturne/stock/goth-22.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632521/nocturne/stock/goth-23.jpg",
  "https://res.cloudinary.com/humd4p9h/image/upload/v1788632523/nocturne/stock/goth-24.jpg"
];

export const STOCK_CREDITS = [
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632490/nocturne/stock/goth-01.jpg",
    "title": "Harajuku Girl",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632492/nocturne/stock/goth-02.jpg",
    "title": "beach goth",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632493/nocturne/stock/goth-03.jpg",
    "title": "Shut up God!",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632495/nocturne/stock/goth-04.jpg",
    "title": "Permission Magazine Cover",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632496/nocturne/stock/goth-05.jpg",
    "title": "Crystal",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632498/nocturne/stock/goth-06.jpg",
    "title": "Natalie",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632499/nocturne/stock/goth-07.jpg",
    "title": "WGT 2010 (Wave-Gotik-Treffen)",
    "license": "CC-BY-SA",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632500/nocturne/stock/goth-08.jpg",
    "title": "Shawni, Proprietess of Roderick's Chamber",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632502/nocturne/stock/goth-09.jpg",
    "title": "Revisitation",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632503/nocturne/stock/goth-10.jpg",
    "title": "Daughter of the night",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632505/nocturne/stock/goth-11.jpg",
    "title": "Theatre Des Vampires",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632506/nocturne/stock/goth-12.jpg",
    "title": "Crystal",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632507/nocturne/stock/goth-13.jpg",
    "title": "Alix Lambert",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632509/nocturne/stock/goth-14.jpg",
    "title": "Girl 13",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632510/nocturne/stock/goth-15.jpg",
    "title": "Ben Chisholm",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632511/nocturne/stock/goth-16.jpg",
    "title": "Contemplative Templar",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632513/nocturne/stock/goth-17.jpg",
    "title": "A word from your god",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632514/nocturne/stock/goth-18.jpg",
    "title": "gothic",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632516/nocturne/stock/goth-19.jpg",
    "title": "Downtown. Underground.",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632518/nocturne/stock/goth-20.jpg",
    "title": "The Constellations tattoo",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632518/nocturne/stock/goth-21.jpg",
    "title": "The Lodger (1944)",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632519/nocturne/stock/goth-22.jpg",
    "title": "IMG_5391a",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632521/nocturne/stock/goth-23.jpg",
    "title": "Derrickatu, Phantom der Nacht",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  },
  {
    "url": "https://res.cloudinary.com/humd4p9h/image/upload/v1788632523/nocturne/stock/goth-24.jpg",
    "title": "The Boy in the Frame",
    "license": "CC-BY",
    "credit": "via Openverse / Flickr"
  }
];
