// One-off script: uploads the curated goth stock set to Cloudinary and
// writes server/src/stockPhotos.js (URL manifest used by seed.js).
// Usage: npm run upload-stock
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
dotenv.config();

import { v2 as cloudinary } from 'cloudinary';
import { isCloudinaryEnabled } from './utils/cloudinary.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

if (!isCloudinaryEnabled()) {
  console.error('Cloudinary is not configured. Set CLOUDINARY_* vars in server/.env');
  process.exit(1);
}

const candidates = JSON.parse(fs.readFileSync(path.join(__dirname, 'stockCandidates.json'), 'utf8'));

const uploadOne = async (item, publicId) => {
  const res = await cloudinary.uploader.upload(item.src, {
    folder: 'nocturne/stock',
    public_id: publicId,
    resource_type: 'image',
    overwrite: true,
    context: { caption: item.title, credit: item.credit },
    transformation: [{ width: 1080, height: 1350, crop: 'limit', quality: 'auto', fetch_format: 'auto' }]
  });
  return { url: res.secure_url, publicId: res.public_id, title: item.title, license: item.license, credit: item.credit };
};

const out = { femme: [], masc: [] };
let n = 0;
for (const group of ['femme', 'masc']) {
  for (const item of candidates[group]) {
    n += 1;
    const publicId = `goth-${String(n).padStart(2, '0')}`;
    try {
      const uploaded = await uploadOne(item, publicId);
      out[group].push(uploaded);
      console.log(`ok ${publicId} ${uploaded.url.slice(0, 70)}`);
    } catch (err) {
      console.error(`FAIL ${publicId} (${item.title}):`, err?.message || err);
    }
  }
}

const manifest =
  `// GENERATED by npm run upload-stock — do not edit by hand.\n` +
  `// Goth-culture stock portraits hosted on Cloudinary (folder nocturne/stock).\n` +
  `// Sources: CC-BY / CC-BY-SA images via Openverse (see stockCandidates.json).\n` +
  `export const STOCK_FEMME = ${JSON.stringify(out.femme.map(p => p.url), null, 2)};\n\n` +
  `export const STOCK_MASC = ${JSON.stringify(out.masc.map(p => p.url), null, 2)};\n\n` +
  `export const STOCK_CREDITS = ${JSON.stringify([...out.femme, ...out.masc].map(p => ({ url: p.url, title: p.title, license: p.license, credit: p.credit })), null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'stockPhotos.js'), manifest);
console.log(`\nDone: ${out.femme.length} femme + ${out.masc.length} masc uploaded. Manifest written to stockPhotos.js`);
process.exit(0);
